### ISSUE TITLE
Cambio de idioma

### ISSUE THREAD

**Issue by oneeyedman** [RLadiesMadrid/2017_CallOfData#18]
Buenas, he añadido en zeplin el cambio de idioma. Echad un ojo que tiene un poco de truco ya que en tablet uso "EN" y el botón es algo más pequeño.
![screen shot 2018-04-28 at 14 56 35](https://user-images.githubusercontent.com/1732678/39396749-6fec3fae-4af4-11e8-85c5-9e9fcf28c655.png)

El funcionamiento será el siguiente: 
* El idioma por defecto es siempre español, así que el enlace por defecto será a la página en inglés
* Si se pulsa el link, lleva a la página y allí, claro, estará la vuelta a español.
Esto es como más prioritario porque una vez implementado ya todo el mundo puede cambiar textos para las traducciones.

**Comment by chucheria** [comment]
Estamos traduciendo los textos entre @mariamedp @nimbusaeta y yo. Los subiremos a issues aquí para que todo esté identificado.
