### ISSUE TITLE
Opción EVENTO en el menú móvil

### ISSUE THREAD

**Issue by oneeyedman** [RLadiesMadrid/2017_CallOfData#26]
La opción de menú **evento** debería ser una ancla al módulo de la descripción del evento:  

![screen shot 2018-04-29 at 01 12 57](https://user-images.githubusercontent.com/1732678/39401647-7c112636-4b4a-11e8-9acf-5ea1429183e1.png)

Además, debería cerrar el menú móvil si se hace clic desde el.

Cómo lo veis, @jdonsan y @RgomezBertoli?

**Comment by chucheria** [comment]
No se cierra el menú cuando clickas en evento.
