### ISSUE TITLE
Módulo de ponentes

### ISSUE THREAD

**Issue by oneeyedman** [RLadiesMadrid/2017_CallOfData#36]
Ya está actualizado en zeplin el módulo de los ponentes:  

![ponentes](https://user-images.githubusercontent.com/1732678/39767144-4fcb78a8-52e6-11e8-93f5-8c8f037dee91.png)

Va a ser un módulo de tabs, donde cada pestaña será la foto de un ponente. Ahora hay 4 pero llegaremos a 6. 

Ya, estaréis pensando que los anchos que trabajamos no son divisibles entre 6 y es verdad pero os propongo meter las imágenes como background con un background-size:cover para que podamos jugar con que algún tab tenga 1px más de ancho mientras que todos compartan la altura.

## funcionamiento

Por defecto las fotos aparecen desaturadas (por css) y al 30-50% de opacidad, la primera (o mejor, un ponente random) saldrá como activo y su foto en colores y con el resaltado. Si se hace click, en otro ponente, pues el activo a gris y el nuevo a activo.

El título de la charla irá centrado, si los nombres de la charla son larguísimos pongamos un ancho máximo, de manera que el título crezca hacia abajo pero el icono se quede arriba.

> Si necesitáis la fontawesome pro, pedidnosla a @chucheria o a mi, y os generamos un enlace para el proyecto

Sería guay si el nombre de la charla enlaza con la agenda.

**Comment by chucheria** [comment]
> Sería guay si el nombre de la charla enlaza con la agenda.

Aún no hemos asignado las horas de las charlas pero lo hacemos esta semana. Aunque no lo publicaremos hasta que no hayamos elegido las lightnings.

**Comment by oneeyedman** [comment]
@jdonsan, ya lo teneis actualizado en Zeplin

**Comment by codenares** [comment]
Redes sociales de ponentes incluídas

**Comment by chucheria** [comment]
Se nos ha colado un @codenares  😜
