### ISSUE TITLE
Celeste Durán

### ISSUE THREAD

**Issue by nimbusaeta** [RLadiesMadrid/2017_CallOfData#37]
# Bio
## ES
**Celeste Durán** es arquitecta Big Data en Datatons. Estudió Ingeniería Técnica de Telecomunicaciones, especialidad en Telemática, en la Universidad Carlos III de Madrid (UC3M) y Máster en Sistemas Informáticos y Telemáticos en la Universidad Rey Juan Carlos de Madrid (URJC). En el período en la UC3M participó en proyectos de investigación, llegando a publicar en varias revistas. Sus inicios profesionales han estado muy ligados al área de sistemas y ha llevado una gran trayectoria dentro de la administración de sistemas e IT. En 2015 da el salto al mundo de los datos siendo una de las pocas mujeres españolas dentro de este área.

## EN 
**Celeste Durán** works as a Big Data architect at Datatons. She studied Telecommunications Engineering at the Universidad Carlos III de Madrid (UC3M), specializing in Telematics, and holds a Master's degree in Information and Telematics Systems by the Universidad Rey Juan Carlos de Madrid (URJC). She participated in research projects, having published in several journals. Her professional beginnings were very close to the systems field, and she has developed a great career within systems administration and IT. In 2015 she leaped into the data world, becoming one of the few Spanish women in this area.

# Abstract
## ES
Caminando hacia el Big Data

## EN
Walking into Big Data

# SOCIAL
LinkedIn: https://www.linkedin.com/in/maria-celeste-duran-gonzalez-477b46113/
Twitter: https://twitter.com/mceduran

**Comment by chucheria** [comment]
Hecho, cierro el issue, thanks!
