### ISSUE TITLE
Aurora Barrero

### ISSUE THREAD

**Issue by nimbusaeta** [RLadiesMadrid/2017_CallOfData#38]
## ES

**Aurora Barrero** es cofundadora de CTO’s Land y Aika Ventures, presidenta de Astur Valley, asociación asturiana de startups, decana del Colegio profesional de Graduados en Ingeniería Informática e Ingenieros Técnicos en Informática del Principado de Asturias y directora del capítulo de Startup Grind en Asturias. Es doctora en Ingeniería Informática por la Universidad de Oviedo. Organiza varias iniciativas relacionadas con el sector tecnológico y las startups, como Google Developers Group, Women Techmakers y Legal Hackers en Asturias.

## EN

**Aurora Barrero** is cofounder of CTO’s Land and Aika Ventures, president of Asturian start-ups association Astur Valley, dean of the Professional College of Computer Engineers of Asturias, and director of the Asturias' Startup Grind chapter. She holds a PhD in Computer Science by the University of Oviedo. She organizes several technological and start-up initiatives such as Google Developers Group, Women Techmakers and Legal Hackers in Asturias.

# RRSS

https://twitter.com/aurora_barrero
https://www.linkedin.com/in/aurorabarrero

**Comment by chucheria** [comment]
Aurora añadida, cierro el issue. Thanks!
