### ISSUE TITLE
Irene Rodríguez

### ISSUE THREAD

**Issue by chucheria** [RLadiesMadrid/2017_CallOfData#8]
## ES

**Irene Rodríguez**, Senior Data Scientist en Openbank e Investigadora colaboradora en el Departamento de Ingeniería Informática de la Universidad Autónoma de Madrid (UAM). Doctora en Ingeniería Informática y Licenciada en Matemáticas por la UAM. Sus intereses se centran en el ámbito del reconocimiento de patrones y sus aplicaciones prácticas en áreas como la bioinformática, las narices electrónicas, o la industria bancaria, entre otras.

## EN

**Irene Rodríguez** works as Senior Data Scientist at Openbank and Associate Researcher at the Computer Engineering Department of the Autonomous University of Madrid (UAM). Se has a PhD in Computer Engineering and a degree in Mathematics in the UAM. Her interests are pattern recognition and its practical applications in fields such as Bioinformatics, electronic noses, or the banking industry, among others.

**Comment by nimbusaeta** [comment]
Añadir RRSS:

Twitter: https://twitter.com/irenerodluj
LinkedIn: https://www.linkedin.com/in/irenerodluj/

**Comment by chucheria** [comment]
@jdonsan te dejo nombrado por si las puedes añadir.

**Comment by jdonsan** [comment]
Hecho
